###############################################################################
#
#EoxCore commands.
#
###############################################################################

# Define PIP_COMPILE_OPTS=-v to get more information during make upgrade.
PIP_COMPILE = pip-compile --rebuild --upgrade $(PIP_COMPILE_OPTS)

.DEFAULT_GOAL := help

ifdef TOXENV
TOX := tox -- #to isolate each tox environment if TOXENV is defined
endif

# Generates a help message. Borrowed from https://github.com/pydanny/cookiecutter-djangopackage.
help: ## Display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@perl -nle'print $& if m{^[\.a-zA-Z_-]+:.*?## .*$$}' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}'

bumpversion: ## Tag the current version using semantinc versioning and git tags (default: minor)
	# bumpversion major
	bumpversion minor
	# bumpversion patch

clean: ## Remove generated byte code, coverage reports, and build artifacts
	find . -name '__pycache__' -exec rm -rf {} +
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	$(TOX) coverage erase
	rm -fr build/
	rm -fr dist/
	rm -fr *.egg-info

python-test: clean ## Run tests
	$(TOX) coverage run --source="." -m pytest ./eox_core
	$(TOX) coverage report --fail-under=70

python-quality-test:
	$(TOX) pylint ./eox_core
	$(TOX) pycodestyle ./eox_core
	$(TOX) isort --check-only --recursive --diff ./eox_core

javascript-quality-test:
	./node_modules/.bin/eslint ./eox_core/**/*.js*

run-tests: python-test python-quality-test javascript-quality-test

upgrade: export CUSTOM_COMPILE_COMMAND=make upgrade
upgrade: ## update the requirements/*.txt files with the latest packages satisfying requirements/*.in
	pip install -qr requirements/pip-tools.txt
	# Make sure to compile files after any other files they include!
	$(PIP_COMPILE) -o requirements/pip-tools.txt requirements/pip-tools.in
	$(PIP_COMPILE) -o requirements/base.txt requirements/base.in
	$(PIP_COMPILE) -o requirements/test.txt requirements/test.in
	$(PIP_COMPILE) -o requirements/tox.txt requirements/tox.in
	# Let tox control the Django, and django-filter version for tests
	grep -e "^django==" -e "^django-filter==" -e "^celery==" -e "^djangorestframework==" -e "^django-model-utils==" -e "^django-oauth-toolkit==" -e "^django-waffle==" -e "^edx-drf-extensions==" -e "^edx-opaque-keys==" -e "^edx-proctoring==" requirements/test.txt > requirements/django.txt
	sed '/^[dD]jango==/d;/^django-filter==/d;/^celery==/d;/^djangorestframework==/d;/^django-model-utils==/d;/^django-oauth-toolkit==/d;/^django-waffle==/d;/^edx-drf-extensions==/d;/^edx-opaque-keys==/d;/^edx-proctoring==/d' requirements/test.txt > requirements/test.tmp
	mv requirements/test.tmp requirements/test.txt
