# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 21:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eox_core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EoxData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EoxPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('ACTIVATE_USERS', 'activate users'), ('CREATE_USERS', 'create users'), ('ANYTHING', 'anything'), ('ENROLL_USERS', 'enroll users')], max_length=100, verbose_name=eox_core.models.EoxData)),
                ('eoxdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='eox_core.EoxData')),
            ],
        ),
        migrations.CreateModel(
            name='EoxSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=2083, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='eoxpermissions',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eox_core.EoxSite', to_field='site'),
        ),
    ]
